services:
  uiux-web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput --clear &&
             python manage.py makemigrations &&
             python manage.py migrate && 
             python manage.py create_default_admin_user &&
             python manage.py create_test_students &&
             python manage.py create_test_courses &&
             python manage.py runserver 0.0.0.0:8000"
    container_name: uiux-jambot-research
    volumes:
      - static_volume:/app/static
      - media_volume:/app/files
    env_file:
      - .env
    environment:
      DB_NAME: uiux_jambot
      DB_USER: henry
      DB_PASSWORD: henry_yzuic
      DB_HOST: uiux-psqldb
      DB_PORT: 5432
      PROCESS_ON_PRODUCTION: True
    depends_on:
      - uiux-psqldb

  uiux-psqldb:
    image: postgres:13
    container_name: uiux-jambot-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=henry
      - POSTGRES_PASSWORD=henry_yzuic
      - POSTGRES_DB=uiux_jambot

  uiux-nginx:
    image: nginx:latest
    ports:
      - "5418:5418"  # 將 Nginx 暴露到主機的 8080 埠
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static  # 掛載靜態文件
      - media_volume:/app/files    # 掛載媒體文件
    depends_on:
      - uiux-web  # 確保 Django 容器啟動後再啟動 Nginx
volumes:
  postgres_data:
  static_volume:
  media_volume:
