# Generated by Django 4.2.17 on 2025-07-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="課程名稱")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "contents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="course_contents/",
                        verbose_name="課程內容檔案",
                    ),
                ),
                (
                    "content_url",
                    models.URLField(blank=True, null=True, verbose_name="課程內容連結"),
                ),
                (
                    "all_assistive_tool_analysis",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="單元內所有輔助工具分析"
                    ),
                ),
                (
                    "all_prompt_analysis",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="單元內所有提示分析"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "課程",
                "verbose_name_plural": "課程",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="班級名稱")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "學生班級",
                "verbose_name_plural": "學生班級",
                "db_table": "student_classes",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="學號",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="backend.studentclass",
                        verbose_name="班級",
                    ),
                ),
            ],
            options={
                "verbose_name": "學生",
                "verbose_name_plural": "學生",
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="CourseTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="作業名稱")),
                (
                    "contents",
                    models.JSONField(blank=True, default=dict, verbose_name="作業內容"),
                ),
                (
                    "all_assistive_tool_analysis",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="作業內所有輔助工具分析"
                    ),
                ),
                (
                    "all_prompt_analysis",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="作業內所有提示分析"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_tasks",
                        to="backend.course",
                        verbose_name="課程",
                    ),
                ),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_tasks",
                        to="backend.studentclass",
                        verbose_name="班級",
                    ),
                ),
            ],
            options={
                "verbose_name": "課程作業",
                "verbose_name_plural": "課程作業",
                "db_table": "course_tasks",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="student_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="backend.studentclass",
                verbose_name="班級",
            ),
        ),
        migrations.CreateModel(
            name="StudentCourseTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="student_tasks/",
                        verbose_name="作業檔案",
                    ),
                ),
                (
                    "task_link",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="作業連結"
                    ),
                ),
                (
                    "assistive_tool_analysis",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="輔助工具分析"
                    ),
                ),
                (
                    "prompt_analysis",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="提示分析"
                    ),
                ),
                (
                    "teacher_mark",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="老師評語評分"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_course_tasks",
                        to="backend.course",
                        verbose_name="課程",
                    ),
                ),
                (
                    "course_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_course_tasks",
                        to="backend.coursetask",
                        verbose_name="課程作業",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_course_tasks",
                        to="backend.student",
                        verbose_name="學生",
                    ),
                ),
            ],
            options={
                "verbose_name": "學生課程作業",
                "verbose_name_plural": "學生課程作業",
                "db_table": "student_course_tasks",
                "unique_together": {("student", "course_task")},
            },
        ),
        migrations.CreateModel(
            name="StudentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_courses",
                        to="backend.course",
                        verbose_name="課程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_courses",
                        to="backend.student",
                        verbose_name="學生",
                    ),
                ),
            ],
            options={
                "verbose_name": "學生課程",
                "verbose_name_plural": "學生課程",
                "db_table": "student_courses",
                "unique_together": {("student", "course")},
            },
        ),
    ]
