# Generated by Django 4.2.17 on 2025-07-16 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_loginattempt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["-student_class_id", "student_id"],
                "verbose_name": "學生",
                "verbose_name_plural": "學生",
            },
        ),
    ]
