# Generated by Django 4.2.17 on 2025-08-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_student_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="content_url",
        ),
        migrations.RemoveField(
            model_name="course",
            name="contents",
        ),
        migrations.AddField(
            model_name="coursetask",
            name="content_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="course_contents/",
                verbose_name="課程內容檔案",
            ),
        ),
        migrations.AddField(
            model_name="coursetask",
            name="content_url",
            field=models.URLField(blank=True, null=True, verbose_name="課程內容連結"),
        ),
    ]
