# Generated by Django 4.2.17 on 2025-08-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_remove_course_content_url_remove_course_contents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetask",
            name="contents",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="作業內容"
            ),
        ),
    ]
