# Generated by Django 4.2.17 on 2025-08-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_alter_coursetask_contents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetask",
            name="content_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="course_task_files/",
                verbose_name="課程內容檔案",
            ),
        ),
    ]
