# Generated by Django 4.2.17 on 2025-08-24 16:19

import backend.models.course_tasks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_alter_coursetask_content_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetask",
            name="contents",
            field=models.JSONField(
                blank=True,
                default=backend.models.course_tasks.get_default_contents,
                null=True,
                verbose_name="作業內容",
            ),
        ),
    ]
