# Generated by Django 4.2.17 on 2025-08-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_alter_coursetask_contents"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcoursetask",
            name="ocr_content",
            field=models.TextField(blank=True, null=True, verbose_name="OCR 處理後的文本內容"),
        ),
    ]
