# Generated by Django 4.2.17 on 2025-08-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_studentcoursetask_ocr_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcoursetask",
            name="keyword_analysis",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="關鍵詞分析"
            ),
        ),
    ]
