# Generated by Django 4.2.17 on 2025-09-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_studentcoursetask_keyword_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcoursetask",
            name="is_analyzed",
            field=models.BooleanField(default=False, verbose_name="是否已分析"),
        ),
    ]
