# Generated by Django 4.2.17 on 2025-10-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_studentcoursetask_is_analyzed"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetask",
            name="all_keyword_analysis",
            field=models.JSONField(blank=True, default=dict, verbose_name="作業內所有關鍵字分析"),
        ),
    ]
