# Generated by Django 4.2.17 on 2026-05-08 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_coursetask_all_keyword_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("normal", "一般課程"), ("chat", "對話課程")],
                default="normal",
                max_length=20,
                verbose_name="課程類型",
            ),
        ),
        migrations.CreateModel(
            name="StudentCourseChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_content",
                    models.TextField(blank=True, null=True, verbose_name="使用者詢問問題"),
                ),
                (
                    "ai_response",
                    models.TextField(blank=True, null=True, verbose_name="AI 回應內容"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_course",
                        to="backend.course",
                        verbose_name="課程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="學生",
                    ),
                ),
            ],
            options={
                "verbose_name": "學生課程作業",
                "verbose_name_plural": "學生課程作業",
                "db_table": "student_course_chats",
                "unique_together": {("student", "course")},
            },
        ),
    ]
