# Generated by Django 4.2.17 on 2026-05-08 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_course_course_type_studentcoursechat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcoursechat",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="backend.course",
                verbose_name="課程",
            ),
        ),
    ]
