# Generated by Django 4.2.17 on 2026-05-08 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_studentcoursechat_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentcoursechat",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "學生課程聊天",
                "verbose_name_plural": "學生課程聊天",
            },
        ),
        migrations.AlterUniqueTogether(
            name="studentcoursechat",
            unique_together=set(),
        ),
    ]
